
CREATE TABLE IF NOT EXISTS policies (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                        business_id BIGINT NOT NULL,

                                        owner_id BIGINT NOT NULL,

                                        policy_number VARCHAR(100) NOT NULL UNIQUE,

    policy_type VARCHAR(50) NOT NULL,

    coverage_amount DECIMAL(19,2) NOT NULL,

    premium_amount DECIMAL(19,2) NOT NULL,

    start_date DATE NOT NULL,

    end_date DATE NOT NULL,

    status VARCHAR(30) NOT NULL,

    description VARCHAR(1000),

    created_at TIMESTAMP NOT NULL,

    updated_at TIMESTAMP NOT NULL
    );

CREATE UNIQUE INDEX IF NOT EXISTS idx_policy_number
    ON policies(policy_number);

CREATE INDEX IF NOT EXISTS idx_policy_owner
    ON policies(owner_id);

CREATE INDEX IF NOT EXISTS idx_policy_business
    ON policies(business_id);
