
CREATE TABLE IF NOT EXISTS claims (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                      business_id BIGINT NOT NULL,

                                      policy_id BIGINT NOT NULL,

                                      owner_id BIGINT NOT NULL,

                                      claim_number VARCHAR(100) NOT NULL UNIQUE,

    claim_type VARCHAR(50) NOT NULL,

    incident_date DATE NOT NULL,

    reported_date DATE NOT NULL,

    claimed_amount DECIMAL(15,2) NOT NULL,

    approved_amount DECIMAL(15,2),

    description VARCHAR(4000),

    status VARCHAR(50) NOT NULL,

    assigned_adjuster_id BIGINT,

    created_at TIMESTAMP NOT NULL,

    updated_at TIMESTAMP NOT NULL
    );

CREATE UNIQUE INDEX IF NOT EXISTS idx_claim_number
    ON claims(claim_number);

CREATE INDEX IF NOT EXISTS idx_claim_owner
    ON claims(owner_id);

CREATE INDEX IF NOT EXISTS idx_claim_business
    ON claims(business_id);

CREATE INDEX IF NOT EXISTS idx_claim_policy
    ON claims(policy_id);


CREATE TABLE IF NOT EXISTS recoveries (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                          claim_id BIGINT NOT NULL,

                                          owner_id BIGINT NOT NULL,

                                          recovery_amount DECIMAL(15,2) NOT NULL,

    recovery_source VARCHAR(255),

    description VARCHAR(2000),

    status VARCHAR(50) NOT NULL,

    processed_by BIGINT,

    created_at TIMESTAMP NOT NULL,

    updated_at TIMESTAMP NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_recovery_claim
    ON recoveries(claim_id);

CREATE INDEX IF NOT EXISTS idx_recovery_owner
    ON recoveries(owner_id);


