CREATE TABLE IF NOT EXISTS business_profiles (
                                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                                 owner_id BIGINT NOT NULL,

                                                 business_name VARCHAR(200) NOT NULL,

    registration_number VARCHAR(100) NOT NULL UNIQUE,

    business_type VARCHAR(50) NOT NULL,

    industry VARCHAR(100) NOT NULL,

    address VARCHAR(500) NOT NULL,

    city VARCHAR(100) NOT NULL,

    state VARCHAR(100) NOT NULL,

    postal_code VARCHAR(20) NOT NULL,

    country VARCHAR(100) NOT NULL,

    contact_email VARCHAR(255) NOT NULL,

    contact_phone VARCHAR(30) NOT NULL,

    annual_revenue DECIMAL(19,2),

    employee_count INTEGER,

    established_date DATE,

    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP NOT NULL,

    updated_at TIMESTAMP NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_business_owner_id
    ON business_profiles(owner_id);
